// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: proto/api/v1/api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyReq) Reset() {
	*x = EmptyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyReq) ProtoMessage() {}

func (x *EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyReq.ProtoReflect.Descriptor instead.
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{0}
}

type RemainingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remaining uint32 `protobuf:"varint,1,opt,name=remaining,proto3" json:"remaining,omitempty"`
}

func (x *RemainingResp) Reset() {
	*x = RemainingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemainingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemainingResp) ProtoMessage() {}

func (x *RemainingResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemainingResp.ProtoReflect.Descriptor instead.
func (*RemainingResp) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *RemainingResp) GetRemaining() uint32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

type NewReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount uint32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *NewReq) Reset() {
	*x = NewReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewReq) ProtoMessage() {}

func (x *NewReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewReq.ProtoReflect.Descriptor instead.
func (*NewReq) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *NewReq) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type NewResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remaining uint32 `protobuf:"varint,1,opt,name=remaining,proto3" json:"remaining,omitempty"`
	CreatedAt string `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
}

func (x *NewResp) Reset() {
	*x = NewResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewResp) ProtoMessage() {}

func (x *NewResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewResp.ProtoReflect.Descriptor instead.
func (*NewResp) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *NewResp) GetRemaining() uint32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *NewResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DetailsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remaining uint32 `protobuf:"varint,1,opt,name=remaining,proto3" json:"remaining,omitempty"`
	CreatedAt string `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
}

func (x *DetailsResp) Reset() {
	*x = DetailsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailsResp) ProtoMessage() {}

func (x *DetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailsResp.ProtoReflect.Descriptor instead.
func (*DetailsResp) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *DetailsResp) GetRemaining() uint32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *DetailsResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remaining uint32 `protobuf:"varint,1,opt,name=remaining,proto3" json:"remaining,omitempty"`
}

func (x *UseResp) Reset() {
	*x = UseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseResp) ProtoMessage() {}

func (x *UseResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseResp.ProtoReflect.Descriptor instead.
func (*UseResp) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *UseResp) GetRemaining() uint32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

type StampsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stamps []string `protobuf:"bytes,1,rep,name=stamps,proto3" json:"stamps,omitempty"`
}

func (x *StampsResp) Reset() {
	*x = StampsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StampsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StampsResp) ProtoMessage() {}

func (x *StampsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StampsResp.ProtoReflect.Descriptor instead.
func (*StampsResp) Descriptor() ([]byte, []int) {
	return file_proto_api_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *StampsResp) GetStamps() []string {
	if x != nil {
		return x.Stamps
	}
	return nil
}

var File_proto_api_v1_api_proto protoreflect.FileDescriptor

var file_proto_api_v1_api_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x63, 0x6f, 0x2e, 0x72, 0x62, 0x65,
	0x6c, 0x2e, 0x62, 0x6f, 0x6e, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x0a, 0x0a, 0x08, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x22, 0x2d, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69,
	0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x20, 0x0a, 0x06, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22,
	0x4a, 0x0a, 0x0b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x27, 0x0a, 0x07, 0x55,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69,
	0x6e, 0x69, 0x6e, 0x67, 0x22, 0x24, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x32, 0xd5, 0x02, 0x0a, 0x05, 0x42,
	0x6f, 0x6e, 0x6f, 0x73, 0x12, 0x48, 0x0a, 0x09, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e,
	0x67, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x2e, 0x72, 0x62, 0x65, 0x6c, 0x2e, 0x62, 0x6f, 0x6e, 0x6f,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e,
	0x63, 0x6f, 0x2e, 0x72, 0x62, 0x65, 0x6c, 0x2e, 0x62, 0x6f, 0x6e, 0x6f, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a,
	0x0a, 0x03, 0x4e, 0x65, 0x77, 0x12, 0x18, 0x2e, 0x63, 0x6f, 0x2e, 0x72, 0x62, 0x65, 0x6c, 0x2e,
	0x62, 0x6f, 0x6e, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x63, 0x6f, 0x2e, 0x72, 0x62, 0x65, 0x6c, 0x2e, 0x62, 0x6f, 0x6e, 0x6f, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x03, 0x55, 0x73,
	0x65, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x2e, 0x72, 0x62, 0x65, 0x6c, 0x2e, 0x62, 0x6f, 0x6e, 0x6f,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e,
	0x63, 0x6f, 0x2e, 0x72, 0x62, 0x65, 0x6c, 0x2e, 0x62, 0x6f, 0x6e, 0x6f, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x44, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x2e, 0x72, 0x62, 0x65, 0x6c, 0x2e, 0x62, 0x6f,
	0x6e, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x1d, 0x2e, 0x63, 0x6f, 0x2e, 0x72, 0x62, 0x65, 0x6c, 0x2e, 0x62, 0x6f, 0x6e, 0x6f, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x42,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x2e, 0x72, 0x62,
	0x65, 0x6c, 0x2e, 0x62, 0x6f, 0x6e, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x2e, 0x72, 0x62, 0x65, 0x6c, 0x2e, 0x62,
	0x6f, 0x6e, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_api_v1_api_proto_rawDescOnce sync.Once
	file_proto_api_v1_api_proto_rawDescData = file_proto_api_v1_api_proto_rawDesc
)

func file_proto_api_v1_api_proto_rawDescGZIP() []byte {
	file_proto_api_v1_api_proto_rawDescOnce.Do(func() {
		file_proto_api_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_v1_api_proto_rawDescData)
	})
	return file_proto_api_v1_api_proto_rawDescData
}

var file_proto_api_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_api_v1_api_proto_goTypes = []interface{}{
	(*EmptyReq)(nil),      // 0: co.rbel.bonos.v1.EmptyReq
	(*RemainingResp)(nil), // 1: co.rbel.bonos.v1.RemainingResp
	(*NewReq)(nil),        // 2: co.rbel.bonos.v1.NewReq
	(*NewResp)(nil),       // 3: co.rbel.bonos.v1.NewResp
	(*DetailsResp)(nil),   // 4: co.rbel.bonos.v1.DetailsResp
	(*UseResp)(nil),       // 5: co.rbel.bonos.v1.UseResp
	(*StampsResp)(nil),    // 6: co.rbel.bonos.v1.StampsResp
}
var file_proto_api_v1_api_proto_depIdxs = []int32{
	0, // 0: co.rbel.bonos.v1.Bonos.Remaining:input_type -> co.rbel.bonos.v1.EmptyReq
	2, // 1: co.rbel.bonos.v1.Bonos.New:input_type -> co.rbel.bonos.v1.NewReq
	0, // 2: co.rbel.bonos.v1.Bonos.Use:input_type -> co.rbel.bonos.v1.EmptyReq
	0, // 3: co.rbel.bonos.v1.Bonos.Details:input_type -> co.rbel.bonos.v1.EmptyReq
	0, // 4: co.rbel.bonos.v1.Bonos.Stamps:input_type -> co.rbel.bonos.v1.EmptyReq
	1, // 5: co.rbel.bonos.v1.Bonos.Remaining:output_type -> co.rbel.bonos.v1.RemainingResp
	3, // 6: co.rbel.bonos.v1.Bonos.New:output_type -> co.rbel.bonos.v1.NewResp
	5, // 7: co.rbel.bonos.v1.Bonos.Use:output_type -> co.rbel.bonos.v1.UseResp
	4, // 8: co.rbel.bonos.v1.Bonos.Details:output_type -> co.rbel.bonos.v1.DetailsResp
	6, // 9: co.rbel.bonos.v1.Bonos.Stamps:output_type -> co.rbel.bonos.v1.StampsResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_v1_api_proto_init() }
func file_proto_api_v1_api_proto_init() {
	if File_proto_api_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_api_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemainingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_v1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_v1_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_v1_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetailsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_v1_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_v1_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StampsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_v1_api_proto_goTypes,
		DependencyIndexes: file_proto_api_v1_api_proto_depIdxs,
		MessageInfos:      file_proto_api_v1_api_proto_msgTypes,
	}.Build()
	File_proto_api_v1_api_proto = out.File
	file_proto_api_v1_api_proto_rawDesc = nil
	file_proto_api_v1_api_proto_goTypes = nil
	file_proto_api_v1_api_proto_depIdxs = nil
}
